name: Issue Wildcard SSL
on:
  workflow_dispatch:

jobs:
  issue-ssl-certificate:
    name: Issue SSL certificate
    runs-on: ubuntu-latest
    steps:
      - name: Install acme.sh
        run: curl https://get.acme.sh | sh -s email=hi@hexaorzo.net
      - name: Issue SSL cert
        uses: Menci/acme@v1
        with:
          account-tar: ${{ secrets.ACME_SH_ACCOUNT_TAR }}
          domains: hexaorzo.net
          append-wildcard: true
          arguments: --dns dns_cf --server letsencrypt
          output-fullchain: output/fullchain.pem
          output-key: output/key.pem
          uninstall: false
      - name: Install Doppler CLI
        uses: DopplerHQ/cli-action@v2
      - name: Export SSL
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_SERVICE_TOKEN }}
        run: |
          cd /home/runner/.acme.sh/hexaorzo.net_ecc/
          cat hexaorzo.net.cer | doppler secrets set -p hexaorzo.net -c prd SSL_CERT
          cat hexaorzo.net.key | doppler secrets set -p hexaorzo.net -c prd SSL_KEY
          cat ca.cer | doppler secrets set -p hexaorzo.net -c prd SSL_CA
          cat fullchain.cer | doppler secrets set -p hexaorzo.net -c prd SSL_FULLCHAIN

          
