name: Issue Wildcard SSL
on:
  workflow_dispatch:

jobs:
  issue-ssl-certificate:
    name: Issue SSL certificate
    runs-on: ubuntu-latest
    steps:
      - name: Install acme.sh
        run: curl https://get.acme.sh | sh -s email=hi@hexaorzo.net
      - name: Issue SSL cert
        run: |
          cd /home/runner/.acme.sh
          ./acme.sh --issue --dns dns_cf -d hexaorzo.net -d '*.hexaorzo.net' --server letsencrypt
      - name: Install Doppler CLI
        uses: DopplerHQ/cli-action@v2
